version: '3'
services: 
    app:
        build: .
        container_name: iniciando-django-app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/home/django/app
        ports: 
            - "8000:8000"
        depends_on: 
            - db

    db:
        image: postgres
        container_name: iniciando-django-db
        tty: true
        environment: 
            - POSTGRES_DB=iniciando_django
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
        volumes: 
            - iniciando-django-pgdata:/var/lib/postgresql/data
    # docker volume create iniciando-django-pgdata

volumes:  
    iniciando-django-pgdata:
        external: true
# create new project:
# docker-compose run app django-admin startproject iniciando_com_django